#!/usr/bin/python3
import pandas as pd
import requests
import mysql.connector

mydb2 = mysql.connector.connect(
  host="172.17.0.1",
  port=3306,
  user="root",
  password="Ciocanul12@",
  database="academy_ready"
)

mycursor = mydb2.cursor()
comanda = '''CREATE TABLE city_average(
            city varchar2(255),
            average_salary double,
            number_of_playrs int
            )'''
mycursor.execute(comanda)
mycursor.execute("Show Tables")
r = mycursor.fetchall()
print(r)
