#!/usr/bin/python3


mydb2 = mysql.connector.connect(
  host="172.17.0.2",
  port=3306,
  user="MySQLcontainer",
  password="Ciocanul12@",
  database="academy_ready"
)

mycursor = mydb2.cursor()
mycursor.execute("Show Tables")
r = mycursor.fetchall()
print(r)
