name: hello

on: [push]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name : Run a hello world to test
      run: echo Hello world
    - name : join salary and savings and put them into ready container
      run: |
        pip3 install pandas
        sudo python3 -m pip install --upgrade pip
        pip3 install azure-storage-blob
        pip3 install azure
        sudo python3 merge_salary
